{% set name = "cram" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7da7445af2ce15b90aad5ec4792f857cef5786d71f14377e9eb994d8b8337f2f

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - cram

  commands:
    - cram -h

about:
  home: https://bitheap.org/cram/
  license: GPL-2.0
  license_file: COPYING.txt
  summary: 'A simple testing framework for command line applications'
  license_family: GPL2
  description: |
    Cram is a functional testing framework for command line applications. Cram
    tests look like snippets of interactive shell sessions. Cram runs each command
    and compares the command output in the test with the commands actual output.
  dev_url: https://github.com/brodie/cram

extra:
  recipe-maintainers:
    - nehaljwani
