travis:
  secure:
    BINSTAR_TOKEN: bEFbOicFZTsaewZSLZUSkdAHvpnnVehbMqZRI4CMlhUAnvbPEyJzzGFtBVElJZPAlRSGvYD/922ppEx/vtDbHCGRBFok6T0MRn4uVD/u7QlgEpo9O4XS9xY2hCV7tYDoFZC0eF9xdGz800F+hfm0c7j6qtcbyUXej0fZJTm2mbqnvoJyaYSlNOZs5+PTfGfsZQ+IthbzxWzx/oR9rmy6sxkw5D0AxQsDwadYg4OwwmqoZ0NUU+MMecsJjLzCwC/0ZgnZL8JPhTImBmUxNL3273Vm/JQnh7jbPCrIVX5AnSaiPTjkY1GrNn1Ro1Nbz3+ujSOLHqlGOdXRAb6qAlvrw807H7uFPtSG+GR9M3n2OmNMYb0OspSjfejRA4Jju2qPSUfMfTIklx8CE5W+IJqbsvdbFOBcKI9QysvDBEs6mON4UOcK7cm7WERb1Yxy4MPU2BhHnh+Yfg9Om6OC/f6zZYDqGBYJip2hMRzHxoiemaZJa8euKwu/MhoOpKDK5/Lw7jIgyLT/HBR6g76uOga2XPL0g9T/LDuVWzzSyucPPRUaRbpiW4loCeiUDgJ8kJ26BP31SWUoz5j3ugV148QjAK1+GW6amV6a8JoHAv0dsC9rCwcKhNmddcSN7JTKO/sV4/Lg9pnRV7VO0UgSTRqq+Fw5F1CprwxaOLB+HeTffaw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
