travis:
  secure:
    BINSTAR_TOKEN: f4HVaNGMYrH14+IpV3zsEtPT1FqS8ZzSIg7FEO5tuKwcaO11BXz1HalGZfAnBl+ofUKmyVcEFSQDCYM+uJMO6Hy6kDLwaYnBJUiINB1ixKkCZorEAX+faw941wopW7n2FkhztTqrlVds0usrWnQjV7PTGU40r4cnM5nXfIDnmSORdrmsxhnJkBMrDYxag7P9YmF3PsoabJbsZI4x54m8im/TRfCHRF8mZmcXJzs+mgGqnNPxaIh8queILw61N/nDYvzsgXFfpZU9pvkHmgoeYFyb5Oey0JwMvp+PoyVSKPmBxrEkCb262/lbvitGF2cmnfXxxw1lAxYc8OkRlc+kVe8/CdV4i3CTut1XPj+E5Mw2B66NElFbuyQYYeeZlEyQ+VUUiPb5LIToieTNLbDoFGrpbSGRYhCU2HfSrDGiPiF+MoPfCKu3LoHX5rud6b8DZNdhpTp1k1aX69V+pEgomD+ewnUtgdjHPCaJrdyFU2Cs4oPHORUJ1yM35wawpUb3RGaLTPpX8xJVzWUaHIYWl6hM1hUP4LEqLKBvlpmRCJtAlkj/D5OCbj+v6WsqRZ3/hmPATSgpbn9q0Y7YXV5mB48KvLy/QmwFe+8SGZhEVCkEc3bEgL7ZjyQv1NB5ZpC5q4mgBP7oWYNz/gnZ7Wten/cIQsyG6hOEeqUtg/NX0vo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
